### ISSUE TITLE
Show summary without expanding

### ISSUE THREAD

**Issue by pleasantone** [hugomods/decap-cms#130]
https://github.com/hugomods/decap-cms/blob/0525a84495e71b6303be8b4d73257d783d51d718/hugo.toml#L43

**Comment by razonyang** [comment]
Hmm, I didn't see any problem, do you test `summary = "{{fields.author}}"`?

**Comment by pleasantone** [comment]
I tried both fields.author and fields.authors, neither affects the summary, so my apologies.

All I get is the following when collapsed...
<img width="678" alt="Screenshot 2024-02-01 at 5 37 46 PM" src="https://github.com/hugomods/decap-cms/assets/5339793/5e048af7-75ea-4266-af71-43bc31782c75">

and the following when expanded:
<img width="705" alt="Screenshot 2024-02-01 at 5 38 51 PM" src="https://github.com/hugomods/decap-cms/assets/5339793/f112dddd-7fe1-4915-90f1-6a071601b911">

I was hoping to get a clean text summary when collapsed, but I'm missing something.
Something that looked like:
```
Authors:
> 2 authors: ich, paul
```

**Comment by razonyang** [comment]
I see, it would be much more intuitive without expanding field, but I didn't find a solution before, may need dive into their docs and source code.

Let's keep it open.

**Comment by razonyang** [comment]
I believe we can't configure it by far:

https://github.com/decaporg/decap-cms/blob/a5f4d9ea08e71df9ab7c4c16ef0503de1d1bb6ee/packages/decap-cms-widget-list/src/ListControl.js#L710C17-L710C47

But we can replace it with a new custom widget.

**Comment by razonyang** [comment]
Done, replace `list` widget with `strings` for those fields.

**Comment by pleasantone** [comment]
I haven’t looked carefully at your new code yet, but are you aware of how the list widget works? If there are no fields defined? You might have just duplicated that.

**Comment by razonyang** [comment]
Now it looks like as follows, those field's values are comma-space-separated (`, `) text by default. It's much more intuitive and easy to modify than `list` widget.

![image](https://github.com/hugomods/decap-cms/assets/17720932/348f08cb-3323-456c-ac83-624bf64f0929)

> but are you aware of how the list widget works

Accoding to the code link above, the `list` widget only shows the number of children and the label on the header, the children's values won't be shown unless expanding.

```js
heading={`${items.size} ${listLabel}`}
```
