### ISSUE TITLE
decap-cms @import rules are deprecated

### ISSUE THREAD

**Issue by pleasantone** [hugomods/decap-cms#253]
In assets/decap-cms/scss/index.scss.tmpl we are using @import.

```
WARN  Dart Sass: DEPRECATED [import]: /Users/pst/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugomods/decap-cms@v0.16.1/assets/decap-cms/scss/index.scss.tmpl:0:8: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.

More info and automated migrator: https://sass-lang.com/d/import
WARN  Dart Sass: DEPRECATED [import]: /Users/pst/Library/Caches/hugo_cache/modules/filecache/modules/pkg/mod/github.com/hugomods/decap-cms@v0.16.1/assets/decap-cms/scss/index.scss.tmpl:1:8: Sass @import rules are deprecated and will be removed in Dart Sass 3.0.0.
```

Not related to #221, standalone issue as well.

**Comment by razonyang** [comment]
Since libsass is still supported, we won't drop `import` rule at this moment (libsass doesn't support `use` rule) untile Dart Sass 3 was released, libsass was removed from Hugo, but those warnging should be filterable, I will take a look tonight.

**Comment by razonyang** [comment]
Done, the latest version of this module should remove those warnings (I filtered them out, not resolved).

PS: Requires Hugo `0.139.0` or above.
